### ISSUE TITLE
3Dircadb数据集的artery

### ISSUE THREAD

**Issue by bamboo211** [SuperJunier666/graph_projtct#1]
作者您好，看到您在血管中心线提取中实现了动脉静脉分离，但在3Dircadb数据集中部分病例没有动脉Atery数据集，这里应该怎样解决，非常期待您百忙之中的答复，受限于自身功底，在这一课题中探索很久，希望有机会进一步交流！
Dear author, I noticed that you have achieved arterial and venous separation in the extraction of vascular centerlines, but some cases in the 3Dircadb dataset do not have the arterial Atery dataset. How should we solve this problem? I am looking forward to your reply amidst your busy schedule. Due to my limited knowledge, I have been exploring this topic for a long time. I hope to have the opportunity to further exchange ideas!

**Comment by SuperJunier666** [comment]
The centerline extraction portion did not do arteries and veins separation, but used this code to do centerline extraction for another task, pulmonary arteriovenous data. The code has now been updated to remove extraneous items.

**Comment by SuperJunier666** [comment]
> 作者您好，看到马德里血管中心线提取中实现了动脉静脉分离，但在3Dircadb数据集中部分病例没有动脉静脉分离，这里应该怎样解决，非常期待您百忙之中的答复，自身功底，在这一课题中长期探索，希望有机会进一步交流！ 亲爱的作者，我注意到您在血管中心线的提取上实现了动脉和静脉的分离，但是3Dircadb数据集中有些病例没有动脉Atery数据集。我们应该怎样解决这个问题呢？我期待您在百忙之中给予答复。由于我的知识有限，我已经探索这个话题很长时间了。希望有机会进一步交流！

The centerline extraction portion did not do arteries and veins separation, but used this code to do centerline extraction for another task, pulmonary arteriovenous data. The code has now been updated to remove extraneous items.

**Comment by bamboo211** [comment]
> > 作者您好，看到马德里血管中心线提取中实现了动脉静脉分离，但在3Dircadb数据集中部分病例没有动脉静脉分离，这里应该怎样解决，非常期待您百忙之中的答复，自身功底，在这一课题中长期探索，希望有机会进一步交流！ 亲爱的作者，我注意到您在血管中心线的提取上实现了动脉和静脉的分离，但是3Dircadb数据集中有些病例没有动脉Atery数据集。我们应该怎样解决这个问题呢？我期待您在百忙之中给予答复。由于我的知识有限，我已经探索这个话题很长时间了。希望有机会进一步交流！
> 
> The centerline extraction portion did not do arteries and veins separation, but used this code to do centerline extraction for another task, pulmonary arteriovenous data. The code has now been updated to remove extraneous items.

好的，非常感谢您百忙之中的答复！

**Comment by bamboo211** [comment]
> > > 作者您好，看到马德里血管中心线提取中实现了动脉静脉分离，但在3Dircadb数据集中部分病例没有动脉静脉分离，这里应该怎样解决，非常期待您百忙之中的答复，自身功底，在这一课题中长期探索，希望有机会进一步交流！ 亲爱的作者，我注意到您在血管中心线的提取上实现了动脉和静脉的分离，但是3Dircadb数据集中有些病例没有动脉Atery数据集。我们应该怎样解决这个问题呢？我期待您在百忙之中给予答复。由于我的知识有限，我已经探索这个话题很长时间了。希望有机会进一步交流！
> > 
> > 
> > The centerline extraction portion did not do arteries and veins separation, but used this code to do centerline extraction for another task, pulmonary arteriovenous data. The code has now been updated to remove extraneous items.
> 
> 好的，非常感谢您百忙之中的答复！

Dear author, the paths of the two types of blood vessels mentioned in the center_line_extract. py file will be used in the subsequent 0'resemple. py, 1upreprocessing. py, and other executed files. When performing liver vessel segmentation tasks, synchronization may be required. Looking forward to your update! Due to my limited skills, I would like to ask for your experience in this area. If it is convenient, could you please leave me your contact information. There is very little code in the task of liver vessel segmentation, and the progress of the project is currently at a bottleneck. We look forward to your valuable experience, as well as the materials and papers involved in this project. Please feel free to ask for your advice!

**Comment by SuperJunier666** [comment]
> > > > 作者您好，看到马德里血管中心线提取中实现了动脉静脉分离，但在3Dircadb数据集中部分病例没有动脉静脉分离，这里应该怎样解决，非常期待您百忙之中的答复，自身功底，在这一课题中长期探索，希望有机会进一步交流！ 亲爱的作者，我注意到您在血管中心线的提取上实现了动脉和静脉的分离，但是3Dircadb数据集中有些病例没有动脉Atery数据集。我们应该怎样解决这个问题呢？我期待您在百忙之中给予答复。由于我的知识有限，我已经探索这个话题很长时间了。希望有机会进一步交流！
> > > 
> > > 
> > > The centerline extraction portion did not do arteries and veins separation, but used this code to do centerline extraction for another task, pulmonary arteriovenous data. The code has now been updated to remove extraneous items.
> > 
> > 
> > 好的，非常感谢您百忙之中的答复！
> 
> Dear author, the paths of the two types of blood vessels mentioned in the center_line_extract. py file will be used in the subsequent 0'resemple. py, 1upreprocessing. py, and other executed files. When performing liver vessel segmentation tasks, synchronization may be required. Looking forward to your update! Due to my limited skills, I would like to ask for your experience in this area. If it is convenient, could you please leave me your contact information. There is very little code in the task of liver vessel segmentation, and the progress of the project is currently at a bottleneck. We look forward to your valuable experience, as well as the materials and papers involved in this project. Please feel free to ask for your advice!

是的，在做后续的重采样以及预处理之前，需要做好数据准备，使用center_line_extract.py可以根据肝血管的label提取中心线用于后续步骤，提取中心线算法为[https://github.com/RivuletStudio/rivuletpy]

**Comment by SuperJunier666** [comment]
> > > > 作者您好，看到马德里血管中心线提取中实现了动脉静脉分离，但在3Dircadb数据集中部分病例没有动脉静脉分离，这里应该怎样解决，非常期待您百忙之中的答复，自身功底，在这一课题中长期探索，希望有机会进一步交流！ 亲爱的作者，我注意到您在血管中心线的提取上实现了动脉和静脉的分离，但是3Dircadb数据集中有些病例没有动脉Atery数据集。我们应该怎样解决这个问题呢？我期待您在百忙之中给予答复。由于我的知识有限，我已经探索这个话题很长时间了。希望有机会进一步交流！
> > > 
> > > 
> > > The centerline extraction portion did not do arteries and veins separation, but used this code to do centerline extraction for another task, pulmonary arteriovenous data. The code has now been updated to remove extraneous items.
> > 
> > 
> > 好的，非常感谢您百忙之中的答复！
> 
> Dear author, the paths of the two types of blood vessels mentioned in the center_line_extract. py file will be used in the subsequent 0'resemple. py, 1upreprocessing. py, and other executed files. When performing liver vessel segmentation tasks, synchronization may be required. Looking forward to your update! Due to my limited skills, I would like to ask for your experience in this area. If it is convenient, could you please leave me your contact information. There is very little code in the task of liver vessel segmentation, and the progress of the project is currently at a bottleneck. We look forward to your valuable experience, as well as the materials and papers involved in this project. Please feel free to ask for your advice!

是的，在做后续的重采样以及预处理之前，需要做好数据准备，使用center_line_extract.py可以根据肝血管的label提取中心线用于后续步骤，提取中心线算法为https://github.com/RivuletStudio/rivuletpy
